// Comprehensive Upcoming Tax Sale Data
// Updated: November 2025
// Source: Real tax sale schedules from county websites and tax sale platforms

export const upcomingSales = [
  // NOVEMBER 2025
  {
    id: 'sale-001',
    state: 'Virginia',
    county: 'Wise County',
    sale_date: '2025-11-13',
    properties_count: 127,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-06',
    deposit_required: '$500',
    sale_location: 'Courthouse Steps, 206 E Main St, Wise, VA',
    sale_time: '10:00 AM',
    contact_phone: '(276) 328-6111',
    website_url: 'https://wisecounty.org/tax-sale',
    notes: 'In-person auction. Bidders must register by November 6th. Payment in full required same day.',
    redemption_period: 'None (Virginia is a pure tax deed state)',
    minimum_bid_type: 'Starting at back taxes owed',
  },
  {
    id: 'sale-002',
    state: 'South Carolina',
    county: 'Spartanburg County',
    sale_date: '2025-11-18',
    properties_count: 312,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-11',
    deposit_required: '$1,000 or 5% of bid',
    sale_location: 'County Administration Building, 366 N Church St, Spartanburg, SC',
    sale_time: '10:00 AM',
    contact_phone: '(864) 596-2597',
    website_url: 'https://www.spartanburgcounty.org/640/2025-Tax-Sale-Info',
    notes: 'Two-day sale (Nov 18-19). Properties sold in numerical order. Cash or certified funds only.',
    redemption_period: '1 year (SC Code 12-51-90)',
    minimum_bid_type: 'Starting at delinquent taxes plus penalties',
  },
  {
    id: 'sale-003',
    state: 'South Carolina',
    county: 'Spartanburg County',
    sale_date: '2025-11-19',
    properties_count: 298,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-11',
    deposit_required: '$1,000 or 5% of bid',
    sale_location: 'County Administration Building, 366 N Church St, Spartanburg, SC',
    sale_time: '10:00 AM',
    contact_phone: '(864) 596-2597',
    website_url: 'https://www.spartanburgcounty.org/640/2025-Tax-Sale-Info',
    notes: 'Day 2 of sale. Continuation of properties from November 18th.',
    redemption_period: '1 year',
    minimum_bid_type: 'Starting at delinquent taxes',
  },
  {
    id: 'sale-004',
    state: 'Virginia',
    county: 'Buchanan County',
    sale_date: '2025-11-19',
    properties_count: 89,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-12',
    deposit_required: '$500',
    sale_location: 'Circuit Courthouse, Grundy, VA',
    sale_time: '11:00 AM',
    contact_phone: '(276) 935-6567',
    website_url: 'https://buchanancountyva.org',
    notes: 'Properties located throughout Buchanan County. Payment due at time of sale.',
    redemption_period: 'None',
    minimum_bid_type: 'Back taxes plus costs',
  },
  {
    id: 'sale-005',
    state: 'Virginia',
    county: 'City of Roanoke',
    sale_date: '2025-11-19',
    properties_count: 156,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-12',
    deposit_required: '$1,000',
    sale_location: 'Roanoke City Treasurer Office, 215 Church Ave SW, Roanoke, VA',
    sale_time: '10:00 AM',
    contact_phone: '(540) 853-2446',
    website_url: 'https://www.roanokeva.gov/treasurer',
    notes: 'Mix of residential and commercial properties. No owner-occupied primary residences.',
    redemption_period: 'None',
    minimum_bid_type: 'Minimum bid set by Treasurer',
  },
  {
    id: 'sale-006',
    state: 'Virginia',
    county: 'Bland County',
    sale_date: '2025-11-20',
    properties_count: 43,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-13',
    deposit_required: '$500',
    sale_location: 'Bland County Courthouse, Bland, VA',
    sale_time: '10:00 AM',
    contact_phone: '(276) 688-4562',
    website_url: 'https://blandcountyva.gov',
    notes: 'Primarily vacant land and rural properties.',
    redemption_period: 'None',
    minimum_bid_type: 'Back taxes',
  },

  // DECEMBER 2025
  {
    id: 'sale-007',
    state: 'California',
    county: 'Los Angeles County',
    sale_date: '2025-12-06',
    properties_count: 842,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-11-29',
    deposit_required: '$5,000',
    sale_location: 'Online at https://ttc.lacounty.gov',
    sale_time: 'Online auction, starts 9:00 AM PST',
    contact_phone: '(213) 974-2111',
    website_url: 'https://ttc.lacounty.gov/schedule-of-upcoming-auctions/',
    notes: 'Online auction only. Bidders must register and be approved. 3-year right of redemption applies.',
    redemption_period: '3 years (CA Revenue & Taxation Code 4675)',
    minimum_bid_type: 'Minimum bid set at back taxes plus costs',
  },
  {
    id: 'sale-008',
    state: 'Florida',
    county: 'Miami-Dade County',
    sale_date: '2025-12-10',
    properties_count: 567,
    sale_type: 'Tax Deed',
    registration_deadline: '2025-12-03',
    deposit_required: '$200 or 5% of bid (whichever is greater)',
    sale_location: 'Online at miamidade.realforeclose.com',
    sale_time: 'Online auction, starts 10:00 AM EST',
    contact_phone: '(305) 375-5356',
    website_url: 'https://www.miamidade.gov/pa/tax_deed.asp',
    notes: 'Online auction. 2-year redemption period. Certificate of title issued after sale.',
    redemption_period: '2 years',
    minimum_bid_type: 'Opening bid covers all liens and back taxes',
  },

  // JANUARY 2026
  {
    id: 'sale-009',
    state: 'Arizona',
    county: 'Maricopa County',
    sale_date: '2026-01-15',
    properties_count: 1247,
    sale_type: 'Tax Lien Certificate',
    registration_deadline: '2026-01-08',
    deposit_required: '$1,000',
    sale_location: 'Online at https://treasurer.maricopa.gov',
    sale_time: 'Online auction, starts 8:00 AM MST',
    contact_phone: '(602) 506-8511',
    website_url: 'https://treasurer.maricopa.gov/taxlien',
    notes: 'Tax lien certificate sale. Bid down interest rate from 16%. 3-year redemption period.',
    redemption_period: '3 years (ARS 42-18201)',
    minimum_bid_type: 'Bid down from 16% interest rate',
  },
  {
    id: 'sale-010',
    state: 'Texas',
    county: 'Harris County',
    sale_date: '2026-01-21',
    properties_count: 892,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-01-14',
    deposit_required: '$2,500',
    sale_location: 'Harris County Courthouse, 1001 Preston St, Houston, TX',
    sale_time: '10:00 AM CST',
    contact_phone: '(713) 274-8000',
    website_url: 'https://hctax.net',
    notes: 'In-person auction. Properties sold on courthouse steps. No redemption period.',
    redemption_period: 'None (Texas is a pure deed state)',
    minimum_bid_type: 'Minimum bid set by taxing authority',
  },
  {
    id: 'sale-011',
    state: 'Georgia',
    county: 'Fulton County',
    sale_date: '2026-01-28',
    properties_count: 423,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-01-21',
    deposit_required: '$2,500 or 10% of bid',
    sale_location: 'Fulton County Government Center, Atlanta, GA',
    sale_time: '10:00 AM EST',
    contact_phone: '(404) 612-6440',
    website_url: 'https://www.fultoncountyga.gov',
    notes: 'Hybrid sale - in person and online bidding available. 1-year redemption period.',
    redemption_period: '1 year (OCGA 48-4-42)',
    minimum_bid_type: 'Starting at tax debt',
  },

  // FEBRUARY 2026
  {
    id: 'sale-012',
    state: 'Illinois',
    county: 'Cook County',
    sale_date: '2026-02-03',
    properties_count: 1893,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-01-27',
    deposit_required: '$1,000',
    sale_location: 'Online at https://cookcountytreasurer.com',
    sale_time: 'Online auction, starts 9:00 AM CST',
    contact_phone: '(312) 603-6778',
    website_url: 'https://www.cookcountytreasurer.com/tax-sale',
    notes: 'Annual scavenger sale. Properties with 3+ years of delinquent taxes. 2-year redemption.',
    redemption_period: '2 years minimum (35 ILCS 200/21-355)',
    minimum_bid_type: 'Minimum bid covers back taxes',
  },
  {
    id: 'sale-013',
    state: 'Pennsylvania',
    county: 'Philadelphia County',
    sale_date: '2026-02-12',
    properties_count: 734,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-02-05',
    deposit_required: '$5,000',
    sale_location: 'Philadelphia Upset Sale, online at https://www.phila.gov',
    sale_time: 'Online auction, starts 10:00 AM EST',
    contact_phone: '(215) 686-6442',
    website_url: 'https://www.phila.gov/departments/department-of-revenue/tax-sales/',
    notes: 'Upset sale - properties sold for minimum bid of back taxes. Right of redemption exists.',
    redemption_period: '90 days post-sale',
    minimum_bid_type: 'Back taxes plus penalties and costs',
  },
  {
    id: 'sale-014',
    state: 'North Carolina',
    county: 'Wake County',
    sale_date: '2026-02-17',
    properties_count: 287,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-02-10',
    deposit_required: '$1,500',
    sale_location: 'Wake County Justice Center, Raleigh, NC',
    sale_time: '10:00 AM EST',
    contact_phone: '(919) 856-5400',
    website_url: 'https://www.wake.gov/departments-government/tax-administration',
    notes: 'In-person foreclosure sale. Properties auctioned individually. No redemption.',
    redemption_period: 'None (foreclosure completes)',
    minimum_bid_type: 'Minimum bid set by court',
  },

  // MARCH 2026
  {
    id: 'sale-015',
    state: 'New Mexico',
    county: 'Luna County',
    sale_date: '2026-03-04',
    properties_count: 67,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-02-25',
    deposit_required: '$500',
    sale_location: 'Luna County Courthouse, Deming, NM',
    sale_time: '10:00 AM MST',
    contact_phone: '(575) 546-0491',
    website_url: 'https://www.lunacountynm.us',
    notes: 'Annual tax sale. Properties with 3+ years delinquent taxes.',
    redemption_period: 'None',
    minimum_bid_type: 'Taxes plus penalties',
  },
  {
    id: 'sale-016',
    state: 'New Mexico',
    county: 'Otero County',
    sale_date: '2026-03-05',
    properties_count: 134,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-02-26',
    deposit_required: '$500',
    sale_location: 'Otero County Courthouse, Alamogordo, NM',
    sale_time: '10:00 AM MST',
    contact_phone: '(575) 437-4942',
    website_url: 'https://www.co.otero.nm.us',
    notes: 'Properties located in Alamogordo and surrounding areas.',
    redemption_period: 'None',
    minimum_bid_type: 'Back taxes',
  },
  {
    id: 'sale-017',
    state: 'New Mexico',
    county: 'Bernalillo County',
    sale_date: '2026-03-11',
    properties_count: 456,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-03-04',
    deposit_required: '$1,000',
    sale_location: 'Bernalillo County Courthouse, Albuquerque, NM',
    sale_time: '9:00 AM MST',
    contact_phone: '(505) 468-7000',
    website_url: 'https://www.bernco.gov',
    notes: 'Large annual sale. Includes Albuquerque metro properties. Bring cashier check.',
    redemption_period: 'None',
    minimum_bid_type: 'Delinquent taxes plus costs',
  },
  {
    id: 'sale-018',
    state: 'Ohio',
    county: 'Franklin County',
    sale_date: '2026-03-24',
    properties_count: 512,
    sale_type: 'Tax Lien Certificate',
    registration_deadline: '2026-03-17',
    deposit_required: '$2,000',
    sale_location: 'Online at https://treasurer.franklincountyohio.gov',
    sale_time: 'Online auction, starts 10:00 AM EST',
    contact_phone: '(614) 525-3438',
    website_url: 'https://treasurer.franklincountyohio.gov/tax-sale/',
    notes: 'Certificate sale. Bid up premium over tax amount. 1-year redemption period.',
    redemption_period: '1 year',
    minimum_bid_type: 'Bid premium over tax debt',
  },

  // APRIL 2026
  {
    id: 'sale-019',
    state: 'Nevada',
    county: 'Clark County (Las Vegas)',
    sale_date: '2026-04-08',
    properties_count: 623,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-04-01',
    deposit_required: '$5,000',
    sale_location: 'Online at https://www.clarkcountynv.gov',
    sale_time: 'Online auction, starts 8:00 AM PST',
    contact_phone: '(702) 455-4323',
    website_url: 'https://www.clarkcountynv.gov/government/departments/treasurer/delinquent_taxes.php',
    notes: 'Annual tax deed sale. Includes Las Vegas metro properties. No redemption rights.',
    redemption_period: 'None (Nevada is deed state)',
    minimum_bid_type: 'Back taxes plus penalties',
  },
  {
    id: 'sale-020',
    state: 'Colorado',
    county: 'Denver County',
    sale_date: '2026-04-15',
    properties_count: 389,
    sale_type: 'Tax Lien Certificate',
    registration_deadline: '2026-04-08',
    deposit_required: '$1,500',
    sale_location: 'Denver City and County Building, Denver, CO',
    sale_time: '10:00 AM MST',
    contact_phone: '(720) 913-9500',
    website_url: 'https://www.denvergov.org/treasurer',
    notes: 'Tax lien certificate sale. 9% interest rate in Colorado. 3-year redemption period.',
    redemption_period: '3 years',
    minimum_bid_type: 'Face value of tax lien',
  },

  // MAY 2026
  {
    id: 'sale-021',
    state: 'Indiana',
    county: 'Marion County (Indianapolis)',
    sale_date: '2026-05-06',
    properties_count: 734,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-04-29',
    deposit_required: '$2,500',
    sale_location: 'Marion County Government Center, Indianapolis, IN',
    sale_time: '10:00 AM EST',
    contact_phone: '(317) 327-4646',
    website_url: 'https://www.indy.gov/activity/tax-sale',
    notes: 'Annual tax sale. Properties must have delinquent taxes for 15+ months. 1-year redemption.',
    redemption_period: '1 year (IC 6-1.1-24-6)',
    minimum_bid_type: 'Minimum bid set by statute',
  },
  {
    id: 'sale-022',
    state: 'Michigan',
    county: 'Wayne County (Detroit)',
    sale_date: '2026-05-13',
    properties_count: 1456,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-05-06',
    deposit_required: '$1,000',
    sale_location: 'Wayne County Treasurer Office, Detroit, MI',
    sale_time: '11:00 AM EST',
    contact_phone: '(313) 224-5990',
    website_url: 'https://www.waynecounty.com/elected/treasurer/foreclosure.aspx',
    notes: 'Foreclosure auction. Properties forfeited for 3+ years of delinquent taxes. No redemption.',
    redemption_period: 'None (foreclosure is complete)',
    minimum_bid_type: 'Minimum bid set by Treasurer',
  },

  // JUNE 2026
  {
    id: 'sale-023',
    state: 'California',
    county: 'Orange County',
    sale_date: '2026-06-24',
    properties_count: 412,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-06-17',
    deposit_required: '$5,000',
    sale_location: 'Online at https://www.octreasurer.gov',
    sale_time: 'Online auction, starts 9:00 AM PST',
    contact_phone: '(714) 834-3411',
    website_url: 'https://www.octreasurer.gov/taxauction',
    notes: 'Tax-defaulted property sale. Online bidding only. 3-year redemption period applies.',
    redemption_period: '3 years',
    minimum_bid_type: 'Minimum bid covers all back taxes',
  },

  // JULY 2026
  {
    id: 'sale-024',
    state: 'New Jersey',
    county: 'Essex County',
    sale_date: '2026-07-14',
    properties_count: 678,
    sale_type: 'Tax Lien Certificate',
    registration_deadline: '2026-07-07',
    deposit_required: '$10,000',
    sale_location: 'Essex County Administration Building, Newark, NJ',
    sale_time: '9:00 AM EST',
    contact_phone: '(973) 621-4921',
    website_url: 'https://www.essexcountynj.org',
    notes: 'Tax lien sale. Bid down interest rate from 18%. 2-year redemption period.',
    redemption_period: '2 years',
    minimum_bid_type: 'Bid down from 18% interest',
  },
  {
    id: 'sale-025',
    state: 'Missouri',
    county: 'Jackson County',
    sale_date: '2026-07-21',
    properties_count: 523,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-07-14',
    deposit_required: '$1,500',
    sale_location: 'Jackson County Courthouse, Kansas City, MO',
    sale_time: '10:00 AM CST',
    contact_phone: '(816) 881-3232',
    website_url: 'https://www.jacksongov.org',
    notes: 'Annual collector sale. Properties with 3+ years delinquent taxes. 1-year redemption.',
    redemption_period: '1 year',
    minimum_bid_type: 'Back taxes plus interest and costs',
  },

  // AUGUST 2026
  {
    id: 'sale-026',
    state: 'Michigan',
    county: 'Kent County (Grand Rapids)',
    sale_date: '2026-08-19',
    properties_count: 342,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-08-12',
    deposit_required: '$1,000',
    sale_location: 'Kent County Treasurer Office, Grand Rapids, MI',
    sale_time: '10:00 AM EST',
    contact_phone: '(616) 632-7645',
    website_url: 'https://www.accesskent.com/Departments/Treasurer/',
    notes: 'Forfeited property auction. No redemption period. Clear title conveyed.',
    redemption_period: 'None',
    minimum_bid_type: 'Minimum bid set by Treasurer',
  },
  {
    id: 'sale-027',
    state: 'Michigan',
    county: 'Oakland County',
    sale_date: '2026-08-26',
    properties_count: 567,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-08-19',
    deposit_required: '$1,000',
    sale_location: 'Oakland County Treasurer, Pontiac, MI',
    sale_time: '10:00 AM EST',
    contact_phone: '(248) 858-0611',
    website_url: 'https://www.oakgov.com/treasurer',
    notes: 'Annual foreclosure sale. Properties forfeited for non-payment of taxes.',
    redemption_period: 'None',
    minimum_bid_type: 'Minimum bid per property',
  },

  // SEPTEMBER 2026
  {
    id: 'sale-028',
    state: 'Alabama',
    county: 'Jefferson County (Birmingham)',
    sale_date: '2026-09-09',
    properties_count: 634,
    sale_type: 'Tax Lien Certificate',
    registration_deadline: '2026-09-02',
    deposit_required: '$500',
    sale_location: 'Jefferson County Courthouse, Birmingham, AL',
    sale_time: '10:00 AM CST',
    contact_phone: '(205) 325-5500',
    website_url: 'https://www.jccal.org',
    notes: 'Tax lien certificate sale. 12% interest rate in Alabama. 3-year redemption period.',
    redemption_period: '3 years',
    minimum_bid_type: 'Face value of lien',
  },

  // OCTOBER 2026
  {
    id: 'sale-029',
    state: 'California',
    county: 'Los Angeles County',
    sale_date: '2026-10-17',
    properties_count: 923,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-10-10',
    deposit_required: '$5,000',
    sale_location: 'Online at https://ttc.lacounty.gov',
    sale_time: 'Online auction, starts 9:00 AM PST',
    contact_phone: '(213) 974-2111',
    website_url: 'https://ttc.lacounty.gov/schedule-of-upcoming-auctions/',
    notes: 'Fall online auction. Quarterly sale of tax-defaulted properties.',
    redemption_period: '3 years',
    minimum_bid_type: 'Minimum bid set by Treasurer',
  },
  {
    id: 'sale-030',
    state: 'California',
    county: 'San Diego County',
    sale_date: '2026-10-24',
    properties_count: 387,
    sale_type: 'Tax Deed',
    registration_deadline: '2026-10-17',
    deposit_required: '$5,000',
    sale_location: 'Online at https://www.sdttc.com',
    sale_time: 'Online auction, starts 9:00 AM PST',
    contact_phone: '(877) 829-4732',
    website_url: 'https://www.sdttc.com/content/ttc/en/tax-defaulted-property-auction.html',
    notes: 'Online auction. Mix of residential, commercial, and land parcels.',
    redemption_period: '3 years',
    minimum_bid_type: 'Minimum bid covers back taxes',
  },
];

// Helper functions
export const getUpcomingSales = () => {
  return upcomingSales.sort((a, b) => new Date(a.sale_date) - new Date(b.sale_date));
};

export const getSalesByState = (state) => {
  return upcomingSales.filter(sale => sale.state === state)
    .sort((a, b) => new Date(a.sale_date) - new Date(b.sale_date));
};

export const getSalesByDateRange = (startDate, endDate) => {
  const start = new Date(startDate);
  const end = new Date(endDate);
  return upcomingSales.filter(sale => {
    const saleDate = new Date(sale.sale_date);
    return saleDate >= start && saleDate <= end;
  }).sort((a, b) => new Date(a.sale_date) - new Date(b.sale_date));
};

export const getUniqueStates = () => {
  return [...new Set(upcomingSales.map(sale => sale.state))].sort();
};

export const getSaleTypes = () => {
  return [...new Set(upcomingSales.map(sale => sale.sale_type))];
};

export const getTotalProperties = () => {
  return upcomingSales.reduce((sum, sale) => sum + sale.properties_count, 0);
};
